#!/bin/sh -e

case "$1" in
  configure)
      adduser --system --group --home /var/lib/zerotier-one --no-create-home zerotier-one
      ;;
esac

# avahi explicitly doesn't broadcast over ZeroTier
# so tell avahi to change the config
# avahi already reloads config on file change
sed -i 's/,zt0//' /etc/avahi/avahi-daemon.conf

#DEBHELPER#
