#!/bin/sh -e

case "$1" in
  configure)
      if ! id zerotier-one >>/dev/null 2>&1; then
        useradd --system --user-group --home-dir /var/lib/zerotier-one --no-create-home zerotier-one
      fi
      ;;
esac

# avahi explicitly doesn't broadcast over ZeroTier
# so tell avahi to change the config
# avahi already reloads config on file change
sed -i 's/,zt0//' /etc/avahi/avahi-daemon.conf

#DEBHELPER#
